# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 05:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truecalendar', '0002_auto_20180219_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 2, 19, 5, 51, 56, 378831, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='author',
        ),
        migrations.DeleteModel(
            name='ArticlePost',
        ),
    ]
