# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0004_auto_20180219_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 5, 54, 31, 803335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
