# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0007_auto_20180219_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 6, 2, 10, 398836, tzinfo=utc)),
        ),
    ]
