# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0011_auto_20180219_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='begindate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 48, 33, 535740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='endate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 48, 33, 535766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='importance',
            field=models.CharField(choices=[('1', 'Important'), ('2', 'Fairly Important'), ('3', 'Very Important'), ('4', 'Specially Important'), ('5', 'Extremly Important')], default=1, max_length=1),
        ),
    ]
