# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0012_auto_20180219_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='endate',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 49, 12, 443774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='begindate',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 49, 12, 443749, tzinfo=utc)),
        ),
    ]
