# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0013_auto_20180219_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='begindate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='enddate',
            field=models.DateTimeField(),
        ),
    ]
