# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-19 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0014_auto_20180219_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='begindate',
            new_name='remarkdate',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='enddate',
        ),
    ]
