# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-21 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truecalendar', '0016_auto_20180221_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='done',
            new_name='eventdone',
        ),
    ]
