# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-26 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171227_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 17, 0, 56, 900992, tzinfo=utc)),
        ),
    ]
